### ISSUE TITLE
Working around the pngjs dependency issue with node v0.10.x +

### ISSUE THREAD

**Issue by subblue** [mattdesl/image-sdf#1]
When using node v0.10.x or above you get a warning when installing due to pngjs@0.4.0 used by save-pixels requiring node 0.8.x, so npm doesn't install it as a stand alone global executable.
The only way I could get it to work was to call the following from within the source directory, e.g:
`./bin/cmd.js img.png --s 8 -d 2 -o img-sdf.png`

I wonder if there is a cleaner way around this so it can be used globally as it's a useful little script!
Thanks.

**Comment by mattdesl** [comment]
Looks like maintenance has slowed down a fair bit on pngjs. 

https://github.com/niegowski/node-pngjs/issues/4

@mikolalysenko any ideas or alternatives ?

**Comment by mattdesl** [comment]
@subblue I think the reason it couldn't run is not because of pngjs (which is just a warning) but because I had forgotten to add `bin` field. #2 

Fixed now. Let me know if `npm install -g image-sdf` works out of the box.

**Comment by subblue** [comment]
Excellent, seems to work fine here now.
Thanks :)
