### ISSUE TITLE
Add bin field in package.json

### ISSUE THREAD

**Issue by vorg** [mattdesl/image-sdf#2]
After installing it globally with `npm install image-sdf -g` I get 

`-bash: image-sdf: command not found` on OSX 10.10 with Node 0.12

Maybe because the `bin` field is missing in `package.json`?

``` json
"bin": {
    "image-sdf": "./bin/cmd.js"
 },
```

**Comment by mattdesl** [comment]
D'oh.

Thanks, fixed. Also added a couple tests and a simple way of running the browser example.
