### ISSUE TITLE
browserify?

### ISSUE THREAD

**Issue by nickdesaulniers** [mattdesl/image-sdf#3]
can this be used in a browser, for example, if I passed it an instance of ImageData? possibly in a worker thread? :3

**Comment by mattdesl** [comment]
Yes, the API is undocumented but the `index.js` entry point doesn't require anything out of the ordinary.

It will be extremely slow, if you want something faster check out [distance-transform](https://www.npmjs.com/package/distance-transform).

**Comment by nickdesaulniers** [comment]
cool, thanks, I'll take a look at that.  Thank you for the recommendation!

**Comment by mattdesl** [comment]
If you do find a way of getting `distance-transform` to work easily with SDF rendering, let me know. :smile: I've been meaning to optimize this module.

**Comment by nickdesaulniers** [comment]
https://github.com/scijs/distance-transform/issues/1

**Comment by mourner** [comment]
@mattdesl @nickdesaulniers here's an example of using a distance transform for SDF rendering (I used a different algorithm though): https://mapbox.github.io/tiny-sdf/
